const C = {
  "landing-pages":["conversion","minimal-edits","chatgpt","responsive hierarchy, one primary CTA, concise proof, accessible navigation/content, honest claims, and a mobile path that keeps the main action obvious","One-page launch site~Waitlist signup page~Local service business page~Personal portfolio site~Event landing page~Nonprofit campaign page~App product page~Lead magnet signup page~Coming soon page~Product comparison page"],
  "auth-onboarding":["security","redteam","claude","clear identity/session states, validation, recovery, privacy-aware copy, preservation of unsent local work, and fail-closed server authority","Email and password signup~Magic-link login~Password reset flow~First-run onboarding~Profile setup~Role selection onboarding~Team invite acceptance~Consent and permissions screen~Session-expired recovery~Account deletion flow"],
  "crud-data":["correctness","minimal-edits","chatgpt","create/read/edit/archive behavior, validation, empty/error states, search or filtering where useful, and local-first persistence before optional sync","Simple contact manager~Inventory tracker~Task board~Notes app~Customer list~Expense log~Habit tracker~Reading list~Asset register~Simple CRM pipeline"],
  "dashboards":["ux","minimal-edits","chatgpt","summary metrics, useful filtering, clear verified-vs-placeholder data labels, responsive layout, loading/empty/error states, and drill-down where justified","KPI dashboard~Project status dashboard~Content performance dashboard~Support dashboard~Sales dashboard~Operations dashboard~Learning progress dashboard~Community dashboard~Deployment status dashboard~Audit evidence dashboard"],
  "ecommerce":["pricing","minimal-edits","shopify","real catalog/variant/price/availability boundaries, no invented inventory or discounts, reversible storefront changes, accessible mobile UX, and checkout-safe behavior","Product detail page~Collection page~Cart drawer~Product bundle builder~Size guide experience~Wishlist~Back-in-stock signup~Gift card product page~Store product comparison~Order status lookup"],
  "booking-scheduling":["correctness","minimal-edits","chatgpt","service/resource choice, time selection, timezone/capacity clarity, contact details, confirmation/recovery, and no invented live availability","Appointment booking flow~Class registration~Consultation request~Shared resource booking~Event RSVP flow~Office hours scheduler~Pickup time selector~Volunteer shift signup~Tour booking~Scheduling waitlist"],
  "forms-intake":["correctness","minimal-edits","chatgpt","labels, validation, local draft retention for longer forms, privacy-conscious fields, submit/retry/confirmation states, and accessible error focus","Contact form~Client intake form~Bug report form~Feature request form~Application form~Short survey~Incident intake form~Quote request form~Feedback widget~Document request form"],
  "content-community":["ux","minimal-edits","chatgpt","searchable/readable content, clear authorship/status, local drafts for writing, moderation/reporting boundaries where relevant, and accessible responsive reading","Blog index~Article page~Community feed~Comment thread~Resource library~FAQ center~Product changelog~Testimonial wall~Knowledge base~Community guidelines page"],
  "ai-features":["correctness","minimal-edits","chatgpt","explicit user input, editable AI draft output, no auto-send/publish authority, unsupported-claim warnings, privacy cues, loading/error states, and manual override","Text summarizer feature~Rewrite assistant~FAQ generator from notes~Tag suggestion helper~Support reply drafter~Product description drafter~Meeting summary helper~Simple classification helper~Content idea generator~Prompt builder helper"],
  "automations-integrations":["correctness","minimal-edits","claude","read-only or dry-run first when possible, explicit payload/data mapping, idempotency/retry visibility, secret-safe server boundaries, and explicit mutation/send gates","Webhook receiver starter~CSV import flow~CSV export action~Email notification trigger~Calendar sync boundary~Slack summary workflow~GitHub issue creator~Shopify catalog sync boundary~Zapier catch-hook workflow~Scheduled job status panel"],
  "local-first-offline":["maintainability","lindy","chatgpt","local reads/writes first, reload/offline usefulness, visible sync state, idempotent queued actions, conflict preservation, and cloud sync as coordination rather than sole truth","Offline-first notes~Local draft autosave~Offline-capable form~Sync status indicator~Conflict resolution screen~Offline read cache~Local settings store~Offline action queue~Local backup import/export~Local-first multi-device sync shell"],
  "files-media":["security","minimal-edits","chatgpt","type/size validation, accessible selection/removal, preview or metadata when useful, progress/error/retry states, and server-safe upload/storage boundaries","Image upload UI~Document upload UI~Responsive media gallery~Avatar crop flow~Attachment manager~PDF resource library~Accessible audio player~Video library~Media metadata editor~Drag-and-drop file intake"],
  "search-filter":["ux","minimal-edits","chatgpt","fast understandable query/filter controls, keyboard accessibility, result counts, reset/no-results states, deterministic behavior, and local or URL state where useful","Site search~Table filter bar~Product filters~Resource search~Command palette~Saved filter presets~Advanced search form~Recent searches~Search suggestions~Filter chips pattern"],
  "payments-billing":["pricing","minimal-edits","chatgpt","clear prices/amounts/status, no fake successful charges, explicit confirmation, server-authoritative billing truth, failure/recovery, and reversible pre-commit review","Pricing page~Checkout review step~Billing settings page~Invoice list~Subscription cancellation flow~Plan change flow~Payment failure recovery~Payment receipt page~Trial expiry screen~Donation form shell"],
  "notifications-messaging":["ux","minimal-edits","chatgpt","clear read/send/dismiss states, local drafts where relevant, accessible announcements, explicit send authority, failure recovery, and preference controls","Notification center~Toast notification system~In-app announcement banner~Simple message inbox~Chat interface shell~Email preference center~Push notification permission primer~System status alerts~Reminder settings~Moderation notice flow"],
  "admin-tools":["security","minimal-edits","chatgpt","search/filter/detail views, explicit privileged actions with confirmation, role/capability clarity, immutable evidence where appropriate, and no silent destructive mutation","User admin table~Content admin~Feature flag panel~Audit log viewer~Work queue manager~Moderation queue~Catalog admin~Support ticket admin~System settings admin~Bulk import admin"],
  "accessibility-responsive":["ux","minimal-edits","chatgpt","keyboard path, focus visibility/management, semantic labels, contrast/readability, responsive/touch behavior, zoom/reduced-motion resilience, and real browser proof","Keyboard navigation hardening~Accessible form hardening~Accessible modal/dialog~Responsive data table~Responsive navigation~Contrast-safe UI pass~Reduced-motion support~Touch target hardening~Text zoom resilience~Screen-reader status messaging"],
  "testing-qa":["regression","redteam","claude","small deterministic checks tied to actual user paths, happy and failure states, regression protection without fake-green snapshots, and clear evidence of what was or was not tested","Core smoke test plan~Form validation tests~CRUD behavior tests~Auth flow tests~Responsive UI tests~Accessibility test pass~Offline/local-first tests~Import tests~Search/filter tests~Small regression pack"],
  "deployment-observability":["regression","redteam","claude","version/environment provenance, health/error visibility, no secret leakage, reversible release/rollback boundaries, truthful unknown states, and evidence links rather than decorative green","Health endpoint~Frontend error boundary~Structured logging starter~Environment/deploy banner~Simple status page~Feature probe endpoint or panel~Analytics event map~Release readiness panel~Rollback readiness panel~Runtime error viewer"],
  "security-privacy":["security","redteam","claude","least authority, server-side trust boundaries, safe validation, explicit consent/revocation where relevant, no secret exposure, fail-closed behavior, and evidence-backed security claims","Permission matrix UI~Secret handling audit helper~Browser mutation protection review~Input validation hardening~Privacy settings page~User data export flow~User data deletion workflow~Session security settings~Upload safety boundary~Security header checklist UI"],
};

const UI = /\b(page|dashboard|form|screen|panel|viewer|center|inbox|interface|gallery|library|table|navigation|modal|dialog|banner|settings|product detail|cart|wishlist|booking|scheduler|feed|thread|player|dropzone|palette|pricing|checkout|receipt|site|flow)\b/i;
const NON_UI = new Set(['automations-integrations','testing-qa','deployment-observability','security-privacy']);
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');

function brief(category, scope, title, ui) {
  const proof = ui ? 'and the rendered path has focused Playwright evidence.' : 'and the cheapest valid automated/runtime proof is recorded.';
  return `Build "${title}" for [PROJECT_NAME]. The concrete goal is [GOAL]. Use [STACK] and treat [CONSTRAINTS] as hard constraints. Keep the first shippable slice narrow and preserve existing working behavior. Category requirements for ${category.replace(/-/g,' ')}: ${scope}. Implement the behavior implied by this exact job, not a generic demo. For user-editable state, default to local-first behavior where practical so drafts/core interactions survive reloads or brief offline use; keep auth, secrets, billing, publication, shared coordination, and other server-authoritative truth on the server. Do not invent live integrations, data, availability, payments, or proof. Handle loading, empty, validation, failure, and recovery states relevant to this job. Done when: the primary user path works end-to-end, the failure path is understandable, the change is reversible, ${proof}`;
}

export const builderPrompts = Object.entries(C).flatMap(([category,[riskLens,mode,platform,scope,jobs]]) =>
  jobs.split('~').map((title,index) => {
    const requiresUiProof = !NON_UI.has(category) || UI.test(`${title} ${scope}`);
    return {
      id:`builder.curated.${category}.${String(index+1).padStart(2,'0')}.${slug(title)}|catalog-v1`,
      title:`Builder · ${title}`,
      description:`Beginner-friendly ${category.replace(/-/g,' ')} build recipe with an explicit done condition and proof gate.`,
      pack:`builder-${category}`, familyId:'application.builder', clauseIds:[], platform, stage:'build', modes:[mode], riskLens,
      inputs:['projectName','goal','stack','constraints'], status:'curated', version:'catalog-v1', requiresUiProof,
      instructions:brief(category,scope,title,requiresUiProof),
    };
  })
);
if (builderPrompts.length !== 200) throw new Error(`Builder prompt seed drift: expected 200, got ${builderPrompts.length}`);
